spring.application.name: "crud"

spring:
  datasource:
  url: jdbc:h2:file:./data/testdb
  driverClassName: org.h2.Driver
  jpa:
  database-platform: org.hibernate.dialect.H2Dialect

# Optional: enable H2 console
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console